# check_account tasks/main.yml
- name:  settings.json
  slurp:
    src: "{{ inspection_home }}/data/settings.json"
  register: settings_raw
  delegate_to: localhost
  ignore_errors: yes
- name:  settings.json
  set_fact:
    settings: "{{ settings_raw.content | b64decode | from_json }}"
  when: settings_raw is succeeded
  ignore_errors: yes
- name:  snapshot 
  set_fact:
    account_snapshot_dir: "{{ settings.account_snapshot_dir | default(account_snapshot_dir_default) }}"
- name:  Linux 
  include_tasks: linux.yml
  when: ansible_system == "Linux"
- name:  AIX 
  include_tasks: aix.yml
  when: ansible_system == "AIX"
- name:  OS
  set_fact:
    account_result:
      status: "unevaluated"
      reason: " OS{{ ansible_system }}"
  when:
    - ansible_system != "Linux"
    - ansible_system != "AIX"

- name: Windows check_account
  include_tasks: windows.yml
  when: ansible_os_family == "Windows"
